apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o5ectt6o2-go
  janus-idp.io/tekton: o5ectt6o2-go
  backstage.io/kubernetes-id: o5ectt6o2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o5ectt6o2-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
